org: remotiondev
app: aws-remotion-serverless
service: api-render-video

provider:
  name: aws
  runtime: nodejs14.x
  stage: beta
  region: ap-southeast-2
  iam:
    role: !Sub arn:aws:iam::${AWS::AccountId}:role/remotionLambdaServerlessRole

functions:
  render:
    handler: handler.render
    events:
      - http:
          path: /render
          method: post

plugins:
  - serverless-plugin-typescript
